/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumFormRole } from "./EnumFormRole";
import { IsEnum, IsOptional } from "class-validator";
@InputType()
class FormUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumFormRole,
  })
  @IsEnum(EnumFormRole)
  @IsOptional()
  @Field(() => EnumFormRole, {
    nullable: true,
  })
  role?: "Admin" | "Manager" | "Employee" | null;
}
export { FormUpdateInput };
