/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FormWhereInput } from "./FormWhereInput";
import { Type } from "class-transformer";
import { FormOrderByInput } from "./FormOrderByInput";

@ArgsType()
class FormFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => FormWhereInput,
  })
  @Field(() => FormWhereInput, { nullable: true })
  @Type(() => FormWhereInput)
  where?: FormWhereInput;

  @ApiProperty({
    required: false,
    type: FormOrderByInput,
  })
  @Field(() => FormOrderByInput, { nullable: true })
  @Type(() => FormOrderByInput)
  orderBy?: FormOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { FormFindManyArgs };
